### ISSUE TITLE
Connection timeout with v5.15.0, fine with 5.14.0

### ISSUE THREAD

**Issue by adamdullenty** [sferik/twitter#727] opened 2015-09-14 08:55 UTC
We are having issues with the twitter gem running 5.15.0.

The connection times out after about a minute with:

```
Connection timed out - connect(2) for \"199.16.156.20\" port 
```

On a separate machine (on a separate network) we get the same error with a different IP address:

```
Connection timed out - connect(2) for \"199.16.156.217\" port 
```

I am guessing that these are both IPs for stream.twitter.com (maybe they have a pool of IPs they cycle through?)

No issues reported on their API status page (https://dev.twitter.com/overview/status)

Rolling back to 5.14.0 seems to work fine on both machines.

**Comment by davidcelis** [comment] 2015-09-14 15:44
I think that this is a duplicate of #709

**Comment by adamdullenty** [comment] 2015-09-14 15:56
Apologies, looks like you're right.

**Closed** 2015-09-14 16:57 UTC
